<?php

/**
 * 权限字典「模块」列技术名 → 中文说明（用于表格分组标题与列展示）。
 */
return [
    'all' => '全部模块',
    'dashboard' => '工作台',
    'articles' => '文章',
    'projects' => '项目',
    'categories' => '分类',
    'premium-resources' => '会员资源',
    'side-hustle-cases' => '副业案例',
    'private-traffic-sops' => '私域 SOP',
    'ai-tool-monetization' => 'AI 工具变现',
    'moderation' => '内容审核',
    'comments' => '评论',
    'orders' => '订单',
    'subscriptions' => '会员订阅',
    'svip-custom-subscriptions' => 'SVIP 定制',
    'view-histories' => '浏览历史',
    'users' => '用户',
    'points-ledger' => '积分流水',
    'refund-requests' => '退款申请',
    'invoice-requests' => '发票申请',
    'comment-reports' => '评论举报',
    'email-templates' => '邮件模板',
    'email-logs' => '邮件记录',
    'email-subscriptions' => '邮件订阅',
    'site-testimonials' => '首页评价',
    'announcements' => '公告',
    'system-notifications' => '系统通知',
    'push-notifications' => '站内推送',
    'skin-configs' => '皮肤主题',
    'ad-slots' => '广告位',
    'openclaw-task-logs' => 'OpenClaw 任务日志',
    'settings' => '站点设置',
    'email-settings' => '邮件设置',
    'shared-components' => '共享组件',
    'audit-logs' => '审计日志',
    'publish-audits' => '发布审核',
    'roles' => '后台角色',
    'menus' => '导航菜单',
];
